[versions]

vanniktech-maven-publish = "0.36.0"

android-junit-framework = "2.0.1"
android-tools-build-gradle = "9.0.0"

androidx-material = "1.12.0"
androidx-activity = "1.12.3"
androidx-constraintlayout = "2.2.1"
androidx-appcompat = "1.7.1"
androidx-legacy-support-v4 = "1.0.0"
googlecode-libphonenumber = "9.0.22"
semver4j = "3.1.0"

androidx-espresso-core = "3.7.0"
json = "20251224"
mockito = "5.21.0"
assertj = "3.27.7"
junit-jupiter = "6.0.2"
androidx-test-runner = "1.7.0"

[plugins]
android-junit-framework = { id = "de.mannodermaus.android-junit", version.ref = "android-junit-framework" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }

[libraries]

android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-tools-build-gradle" }

androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "androidx-legacy-support-v4" }
androidx-material = { module = "com.google.android.material:material", version.ref = "androidx-material" }
googlecode-libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "googlecode-libphonenumber" }
semver4j = { module = "com.vdurmont:semver4j", version.ref = "semver4j" }

androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso-core" }
json = { module = "org.json:json", version.ref = "json" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
