---
name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    name: âœï¸ Draft release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-22.04

    steps:
      - name: ðŸš€ Run Release Drafter
        id: release_drafter
        uses: release-drafter/release-drafter@v6.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate VCODE
        id: generate_vcode
        run: echo "vcode=$(expr $(date +%s) / 60 - 26797800)" >> $GITHUB_OUTPUT

      - name: Set version
        run: |
          sed -i 's/$version/${{ steps.release_drafter.outputs.name }}/g' app/version.properties
          sed -i 's/$code/${{ steps.generate_vcode.outputs.vcode }}/g' app/version.properties

      - name: Commit version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Configure release information
          branch: release/next
          create_branch: true
          push_options: '--force'

      - name: Change target
        run: |
          curl -X PATCH \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -H 'Accept: application/vnd.github.v3+json' \
          -H 'Content-Type: application/json' \
          "https://api.github.com/repos/frimtec/secure-sms-proxy/releases/${{ steps.release_drafter.outputs.id }}" \
          -d '{"tag_name": "${{ steps.release_drafter.outputs.name }}", "target_commitish": "refs/heads/release/next"}'
